insert into veriler(site, urun, fiyat) values('Teknosa','Apple iPhone 8 ',600000)
insert into veriler(site, urun, fiyat) values('Hepsiburada','Apple iPhone 8 ',612000)
insert into veriler(site, urun, fiyat) values('MediaMarkt','Apple iPhone 8 ',586900)
insert into veriler(site, urun, fiyat) values('Amazon','Apple iPhone 8 ',600000)
insert into veriler(site, urun, fiyat) values('Teknosa','PS 4',399900)
insert into veriler(site, urun, fiyat) values('Hepsiburada','PS 4',399900)
insert into veriler(site, urun, fiyat) values('MediaMarkt','PS 4',399900)
insert into veriler(site, urun, fiyat) values('Amazon','PS 4',385000)
insert into veriler(site, urun, fiyat) values('Teknosa','Apple MacBook Pro',1099900)
insert into veriler(site, urun, fiyat) values('Hepsiburada','Apple MacBook Pro',1125000)
insert into veriler(site, urun, fiyat) values('MediaMarkt','Apple MacBook Pro',1089900)
insert into veriler(site, urun, fiyat) values('Amazon','Apple MacBook Pro',1345000)
